In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("/content/sample_data/nist_ir_info.csv")

## Feature Selection

### Drop features that are mostly null

In [13]:
df.info()
df.sample()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19582 entries, 0 to 19581
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cID                19582 non-null  object
 1   name               19582 non-null  object
 2   inchi              19000 non-null  object
 3   mp                 2589 non-null   object
 4   bp                 1679 non-null   object
 5   sID                19582 non-null  int64
 6   filename           19582 non-null  object
 7   state              18760 non-null  object
 8   state_original     18776 non-null  object
 9   resolution         10436 non-null  object
 10  spectrometer       12910 non-null  object
 11  original_spectrum  9679 non-null   object
 12  collection         10655 non-null  object
 13  origin             18812 non-null  object
 14  owner              19582 non-null  object
 15  source_reference   9727 non-null   object
 16  nist_source        19582 non-null  object
 17  date               10791 non-null  object
dtypes: int64(1), object(17)
memory usage: 2.7+ MB

,cID,name,inchi,mp,bp,sID,filename,state,state_original,resolution,spectrometer,original_spectrum,collection,origin,owner,source_reference,nist_source,date
9967,C354336,"Ethane, pentafluoro-","InChI=1S/C2HF5/c3-1(4)2(5,6)7/h1H",-102.78 C,-48.55 C,16,C354336_IR_16.jdx,gas,gas,0.964,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01

In [11]:
df_with_mp = df[df['mp'].notna()]
df_with_mp.sample(50)

,cID,name,inchi,mp,bp,sID,filename,state,state_original,resolution,spectrometer,original_spectrum,collection,origin,owner,source_reference,nist_source,date
2367,C106978,Butane,"InChI=1S/C4H10/c1-3-4-2/h3-4H2,1-2H3",-138.35 C,-0.5 C,19,C106978_IR_19.jdx,gas,gas,0.482,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
8464,C2551624,Sulfur hexafluoride,"InChI=1S/F6S/c1-7(2,3,4,5)6",-50.5 C,-63.9 C (sublimes),19,C2551624_IR_19.jdx,gas,gas,0.241,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
16358,C7383702,"1,3,5-Benzenetricarboxylic acid, triphenyl ester",InChI=1S/C27H18O6/c28-25(31-22-10-4-1-5-11-22)...,171 C,NaN,0,C7383702_IR_0.jdx,solid,"SOLID (SPLIT MULL), FLUOROLUBE FOR 3800-1330 C...",2,DOW KBr FOREPRISM-GRATING,cob8651,COBLENTZ III,DOW CHEMICAL COMPANY,COBLENTZ SOC. Collection (C) 2018 copyright by...,COBLENTZ NO. 08651,COBLENTZ,1965/01/20
7552,C213467,Picene,InChI=1S/C22H14/c1-3-7-17-15(5-1)9-11-21-19(17...,364 C,NaN,0,C213467_IR_0.jdx,solid,"SOLID (SPLIT MULL, FLUOROLUBE FOR 3800-1330 AN...",4,DOW KBr FOREPRISM-GRATING,cob10604,COBLENTZ III,DOW CHEMICAL COMPANY,COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 10604,COBLENTZ,1962/11/14
19196,C95873088,"Alpha,alpha'-diacetyl-n,n'-dibenzyl-glutaramide",InChI=1S/C23H26N2O4/c1-16(26)20(22(28)24-14-18...,170-171 C,NaN,0,C95873088_IR_0.jdx,solid,SOLID (KBr PRESSING),4,"Not specified, most likely a prism, grating, o...",cob4411,COBLENTZ,"EASTMAN KODAK COMPANY, RESEARCH LABORATORIES, ...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 4411,COBLENTZ,"Not specified, most likely prior to 1970"
14584,C627123,Propylcarbamate,"InChI=1S/C4H9NO2/c1-2-3-7-4(5)6/h2-3H2,1H3,(H2...",60-62 C,NaN,0,C627123_IR_0.jdx,solid,SOLID (MINERAL OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob2777,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 2777,COBLENTZ,"Not specified, most likely prior to 1970"
13000,C56630309,"Octanamide, N-(2-mercaptoethyl)-",InChI=1S/C10H21NOS/c1-2-3-4-5-6-7-10(12)11-8-9...,49-50 C,NaN,0,C56630309_IR_0.jdx,solid,SOLID (MINERAL OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob4553,COBLENTZ,"ARTHUR D. LITTLE, INC.",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 4553,COBLENTZ,"Not specified, most likely prior to 1970"
16865,C75730,Tetrafluoromethane,"InChI=1S/CF4/c2-1(3,4)5",-150 C,-129 C,13,C75730_IR_13.jdx,gas,gas,0.964,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
12545,C5437989,p-Acetoacetanisidide,InChI=1S/C11H13NO3/c1-8(13)7-11(14)12-9-3-5-10...,116 C,NaN,0,C5437989_IR_0.jdx,solid,"SOLID (SPLIT MULL, FLUOROLUBE FOR 3800-1330 AN...",4,BECKMAN IR-9 (GRATING),cob10290,COBLENTZ III,DOW CHEMICAL COMPANY,COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 10290,COBLENTZ,1965/07/13
19199,C95885,"1,3-Benzenediol, 4-chloro-","InChI=1S/C6H5ClO2/c7-5-2-1-4(8)3-6(5)9/h1-3,8-9H",105-106 C,NaN,1,C95885_IR_1.jdx,solid,SOLID (MINERAL OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob3773,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 3773,COBLENTZ,"Not specified, most likely prior to 1970"
17368,C781431,"9,10-Dimethylanthracene",InChI=1S/C16H14/c1-11-13-7-3-5-9-15(13)12(2)16...,180-181 C,NaN,1,C781431_IR_1.jdx,solid,SOLID (KBr PELLET),4,"Not specified, most likely a prism, grating, o...",cob3565,COBLENTZ,UNION CARBIDE CORPORATION (CARBON PRODUCTS DIV...,COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 3565,COBLENTZ,"Not specified, most likely prior to 1970"
16075,C71432,Benzene,InChI=1S/C6H6/c1-2-4-6-5-3-1/h1-6H,5.5 C,80.1 C,9,C71432_IR_9.jdx,gas,gas,0.964,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
686,B6005163,Promethazine hydrochloride,InChI=1S/C17H20N2S.ClH/c1-13(18(2)3)12-19-14-8...,230-232 C (SOME DECOMP.),NaN,0,B6005163_IR_0.jdx,solid,SOLID (KCl DISC),2,PERKIN-ELMER 21 (GRATING),cob5163,COBLENTZ III,NaN,COPYRIGHT (C) 1988 by COBLENTZ SOCIETY INC. Co...,COBLENTZ NO. 5163,COBLENTZ,"Not specified, most likely prior to 1970"
7019,C19770844,"P-phenylenediamine, n,n-dimethyl-n',n'-bis(phe...",InChI=1S/C20H20N2O4S2/c1-21(2)17-13-15-18(16-1...,161 C,NaN,0,C19770844_IR_0.jdx,solid,"SOLID (SPLIT MULL), FLUOROLUBE FOR 4000-1340 C...",2,BECKMAN IR-12 (GRATING),cob8531,COBLENTZ III,EASTMAN KODAK COMPANY,Copyright (C) 1987 by the Coblentz Society Col...,COBLENTZ NO. 8531,COBLENTZ,1970/04/02
388,B6002625,Delta-camphor oxime,"InChI=1S/C10H17NO/c1-9(2)7-4-5-10(9,3)6-8(7)11...",118.5-120 C,NaN,0,B6002625_IR_0.jdx,solid,SOLID (MINERAL OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob2625,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 2625,COBLENTZ,"Not specified, most likely prior to 1970"
13908,C609405,"Thiophene, 2-nitro-",InChI=1S/C4H3NO2S/c6-5(7)4-2-1-3-8-4/h1-3H,42-44 C,NaN,0,C609405_IR_0.jdx,solid,SOLID (OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob397,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 397,COBLENTZ,"Not specified, most likely prior to 1970"
17174,C77021,Aprobarbital,InChI=1S/C10H14N2O3/c1-4-5-10(6(2)3)7(13)11-9(...,140-141.5 C,NaN,0,C77021_IR_0.jdx,solid,SOLID (KBr DISC),2,PERKIN-ELMER 21 (GRATING),cob5192,COBLENTZ III,NaN,COBLENTZ SOC. Collection (C) 2018 copyright by...,COBLENTZ NO. 05192,COBLENTZ,1963/02/18
16976,C76164,"Ethane, hexafluoro-","InChI=1S/C2F6/c3-1(4,5)2(6,7)8",-94 C,-79 C,12,C76164_IR_12.jdx,gas,gas,0.964,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
4146,C120616,"1,4-Benzenedicarboxylic acid, dimethyl ester",InChI=1S/C10H10O4/c1-13-9(11)7-3-5-8(6-4-7)10(...,140 C,NaN,2,C120616_IR_2.jdx,solid,SOLID (MULL),4,"Not specified, most likely a prism, grating, o...",cob336,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 336,COBLENTZ,"Not specified, most likely prior to 1970"
15406,C67561,Methyl Alcohol,"InChI=1S/CH4O/c1-2/h2H,1H3",-93.9 C,64.96 C,18,C67561_IR_18.jdx,gas,gas,1.929,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
17370,C781431,"9,10-Dimethylanthracene",InChI=1S/C16H14/c1-11-13-7-3-5-9-15(13)12(2)16...,183 C,NaN,3,C781431_IR_3.jdx,solid,"SOLID (SPLIT MULL, FLUOROLUBE FOR 3800-1333 AN...",4,DOW KBr FOREPRISM-GRATING,cob10676,COBLENTZ III,DOW CHEMICAL COMPANY,COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 10676,COBLENTZ,1966/04/04
9959,C354336,"Ethane, pentafluoro-","InChI=1S/C2HF5/c3-1(4)2(5,6)7/h1H",-102.78 C,-48.55 C,0,C354336_IR_0.jdx,gas,gas,1.929,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
2389,C106990,"1,3-Butadiene","InChI=1S/C4H6/c1-3-4-2/h3-4H,1-2H2",-108.91 C,-4.41 C,13,C106990_IR_13.jdx,gas,gas,0.964,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
8730,C2719235,2-Acetamidothiazole,"InChI=1S/C5H6N2OS/c1-4(8)7-5-6-2-3-9-5/h2-3H,1...",203 C,NaN,0,C2719235_IR_0.jdx,solid,SOLID (KBr PELLET),4,"Not specified, most likely a prism, grating, o...",cob1821,COBLENTZ,"TENNESSEE EASTMAN COMPANY, RESEARCH LABORATORIES",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 1821,COBLENTZ,"Not specified, most likely prior to 1970"
5981,C1634044,"Propane, 2-methoxy-2-methyl-","InChI=1S/C5H12O/c1-5(2,3)6-4/h1-4H3",-109 C,55.2 C,21,C1634044_IR_21.jdx,gas,gas,1.929,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
5103,C140885,"2-Propenoic acid, ethyl ester","InChI=1S/C5H8O2/c1-3-5(6)7-4-2/h3H,1,4H2,2H3",-71.2 C,99.8 C,9,C140885_IR_9.jdx,gas,gas,0.964,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
2286,C106423,p-Xylene,"InChI=1S/C8H10/c1-7-3-5-8(2)6-4-7/h3-6H,1-2H3",13.26 C,138.35 C,5,C106423_IR_5.jdx,gas,gas,1.929,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2001 by the U.S. Secretary of Co...,NaN,QUANT-IR,01/06/01
7923,C2295310,"2,4-Thiazolidinedione","InChI=1S/C3H3NO2S/c5-2-1-7-3(6)4-2/h1H2,(H,4,5,6)",121-123.5 C,NaN,1,C2295310_IR_1.jdx,solid,SOLID (KBr PELLET),4,"Not specified, most likely a prism, grating, o...",cob709,COBLENTZ,"TENNESSEE EASTMAN COMPANY, RESEARCH LABORATORIES",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 709,COBLENTZ,"Not specified, most likely prior to 1970"
9177,C302170,Chloral Hydrate,"InChI=1S/C2H3Cl3O2/c3-2(4,5)1(6)7/h1,6-7H",57 C,98 C,1,C302170_IR_1.jdx,solution,SOLUTION SATURATED (CS2 FOR 2-15 microns),2,PERKIN-ELMER 21 (GRATING),cob5422,COBLENTZ III,THE SQUIBB INSTITUTE FOR MEDICAL RESEARCH,Copyright (C) 1987 by the Coblentz Society Col...,COBLENTZ NO. 5422,COBLENTZ,1965/11/09
2487,C107131,2-Propenenitrile,"InChI=1S/C3H3N/c1-2-3-4/h2H,1H2",-83.5 C,77.5 C,5,C107131_IR_5.jdx,gas,gas,0.241,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
17561,C79016,Trichloroethylene,InChI=1S/C2HCl3/c3-1-2(4)5/h1H,-73 C,87 C,8,C79016_IR_8.jdx,gas,gas,0.125,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
5100,C140885,"2-Propenoic acid, ethyl ester","InChI=1S/C5H8O2/c1-3-5(6)7-4-2/h3H,1,4H2,2H3",-71.2 C,99.8 C,6,C140885_IR_6.jdx,gas,gas,0.241,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
13346,C5851434,"1H-Benzimidazole, 2-(1-methylethyl)-",InChI=1S/C10H12N2/c1-7(2)10-11-8-5-3-4-6-9(8)1...,232-234 C,NaN,0,C5851434_IR_0.jdx,solid,SOLID (KBr PELLET),4,"Not specified, most likely a prism, grating, o...",cob1560,COBLENTZ,"TENNESSEE EASTMAN COMPANY, RESEARCH LABORATORIES",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 1560,COBLENTZ,"Not specified, most likely prior to 1970"
16617,C75092,Methylene chloride,InChI=1S/CH2Cl2/c2-1-3/h1H2,-95.1 C,40 C,12,C75092_IR_12.jdx,gas,gas,0.125,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2001 by the U.S. Secretary of Co...,NaN,QUANT-IR,01/06/01
14954,C637923,"Propane, 2-ethoxy-2-methyl-","InChI=1S/C6H14O/c1-5-7-6(2,3)4/h5H2,1-4H3",-94 C,73.1 C,16,C637923_IR_16.jdx,gas,gas,1.929,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
15467,C67663,Trichloromethane,InChI=1S/CHCl3/c2-1(3)4/h1H,-63.5 C,61.7 C,10,C67663_IR_10.jdx,gas,gas,0.482,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2000 by the U.S. Secretary of Co...,NaN,QUANT-IR,00/02/01
5532,C150685,"Urea, N'-(4-chlorophenyl)-N,N-dimethyl-",InChI=1S/C9H11ClN2O/c1-12(2)9(13)11-8-5-3-7(10...,173 C,NaN,0,C150685_IR_0.jdx,solid,SOLID (0.6 mg / 300 mg KBr DISC),2,PERKIN-ELMER 180 (GRATING),cob9017,COBLENTZ II,K. K. DEB-NCI FREDERICK CANCER RESEARCH CENTER,Copyright (C) 1987 by the Coblentz Society Col...,COBLENTZ NO. 9017,COBLENTZ,1973/08/20
15044,C64175,Ethanol,"InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",-117.3 C,78.5 C,6,C64175_IR_6.jdx,gas,gas,0.482,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
457,B6003029,Ethyl ferrocenoate,InChI=1S/C8H9O2.C5H5.Fe/c1-2-10-8(9)7-5-3-4-6-...,63-64 C,NaN,0,B6003029_IR_0.jdx,solid,SOLID (MINERAL OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob3029,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 3029,COBLENTZ,"Not specified, most likely prior to 1970"
2445,C107062,"Ethane, 1,2-dichloro-",InChI=1S/C2H4Cl2/c3-1-2-4/h1-2H2,-35.36 C,83.47 C,3,C107062_IR_3.jdx,gas,gas,1.929,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2001 by the U.S. Secretary of Co...,NaN,QUANT-IR,01/06/01
15554,C68359,Sulfadiazine,"InChI=1S/C10H10N4O2S/c11-8-2-4-9(5-3-8)17(15,1...",252-256 C,NaN,0,C68359_IR_0.jdx,solid,SOLID (1 mg / 200 mg KBr DISC) VS KBr,2,PERKIN-ELMER 21 (GRATING),cob5169,COBLENTZ III,NaN,COBLENTZ SOC. Collection (C) 2018 copyright by...,COBLENTZ NO. 05169,COBLENTZ,1961/08/21
6888,C192972,Benzo[e]pyrene,InChI=1S/C20H12/c1-2-8-16-15(7-1)17-9-3-5-13-1...,177-180 C,NaN,0,C192972_IR_0.jdx,solid,"SOLID (SPLIT MULL, FLUOROLUBE FOR 3800-1330 AN...",4,DOW KBr FOREPRISM-GRATING,cob10634,COBLENTZ III,DOW CHEMICAL COMPANY,COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 10634,COBLENTZ,1962/11/14
6557,C1818275,"Acetophenone, 2,4,5-trihydroxy",InChI=1S/C8H8O4/c1-4(9)5-2-7(11)8(12)3-6(5)10/...,206-207 C,NaN,0,C1818275_IR_0.jdx,solid,SOLID (KBr PELLET),4,"Not specified, most likely a prism, grating, o...",cob1581,COBLENTZ,"TENNESSEE EASTMAN COMPANY, RESEARCH LABORATORIES",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 1581,COBLENTZ,"Not specified, most likely prior to 1970"
19125,C95476,o-Xylene,"InChI=1S/C8H10/c1-7-5-3-4-6-8(7)2/h3-6H,1-2H3",-25.18 C,144.4 C,22,C95476_IR_22.jdx,gas,gas,0.125,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2001 by the U.S. Secretary of Co...,NaN,QUANT-IR,01/06/01
2803,C108883,Toluene,"InChI=1S/C7H8/c1-7-5-3-2-4-6-7/h2-6H,1H3",-95 C,110.6 C,25,C108883_IR_25.jdx,gas,gas,0.964,IFS66V (Bruker),NaN,IUPAC A,"NIST, Anayltical Chemistry Division, 301-975-3108",COPYRIGHT (C) 1998 by the U.S. Secretary of Co...,NaN,QUANT-IR,98/10/1
13527,C592358,Butyl carbamate,"InChI=1S/C5H11NO2/c1-2-3-4-8-5(6)7/h2-4H2,1H3,...",55-57 C,NaN,0,C592358_IR_0.jdx,solid,SOLID (OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob603,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 603,COBLENTZ,"Not specified, most likely prior to 1970"
19474,C99058,"Benzoic acid, 3-amino-",InChI=1S/C7H7NO2/c8-6-3-1-2-5(4-6)7(9)10/h1-4H...,172 C,NaN,0,C99058_IR_0.jdx,solid,SOLID (SPLIT MULL),4,DOW KBr FOREPRISM-GRATING,cob6776,COBLENTZ III,DOW CHEMICAL COMPANY,COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 6776,COBLENTZ,1963/04/19
694,B6005191,Amodiaquine hydrochloride,InChI=1S/C20H22ClN3O.2ClH.2H2O/c1-3-24(4-2)13-...,150-160 C,NaN,0,B6005191_IR_0.jdx,solid,SOLID (1 mg / 200 mg KCl DISC),2,PERKIN-ELMER 21 (GRATING),cob5191,COBLENTZ III,NaN,COPYRIGHT (C) 1988 by COBLENTZ SOCIETY INC. Co...,COBLENTZ NO. 5191,COBLENTZ,1961/06/27
16122,C71556,"Ethane, 1,1,1-trichloro-","InChI=1S/C2H3Cl3/c1-2(3,4)5/h1H3",-30.41 C,74.1 C,18,C71556_IR_18.jdx,gas,gas,1.929,IFS66V (Bruker),NaN,IUPAC A,"NIST, Analytical Chemistry Division, 301-975-3108",COPYRIGHT (C) 2001 by the U.S. Secretary of Co...,NaN,QUANT-IR,01/06/01
18427,C90415,2-Aminobiphenyl,InChI=1S/C12H11N/c13-12-9-5-4-8-11(12)10-6-2-1...,50-52 C,NaN,1,C90415_IR_1.jdx,solid,SOLID (MINERAL OIL MULL),4,"Not specified, most likely a prism, grating, o...",cob3831,COBLENTZ,"WYANDOTTE CHEMICALS CORP., WYANDOTTE, MICHIGAN...",COBLENTZ SOCIETY Collection (C) 2018 copyright...,COBLENTZ NO. 3831,COBLENTZ,"Not specified, most likely prior to 1970"

### Drop low varience (constant) features

### Drop unique features (except for model output InChI)

### Drop features with high correlatoins to others